In [1]:
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)

import numpy as np
import matplotlib.pyplot as plt
from ecc_burst_new import EccBurstNew
from ecc_prior_new import NewPrior

%load_ext autoreload

%matplotlib inline
%autoreload 2

In [16]:
#Original anchor burst
Mtot = 20 #Total mass
#Conversion factors
GMsun = 1.32712440018e20  # m^3/s^2
c = 299792458 # m/s
Tsun = GMsun / c**3
M2sec = Tsun*Mtot
q = 0.9
Mchirp = q**(3/5)/(1+q)**(6/5)*Mtot

#meta-params for the anchor burst
tstar = -5
tstarM = tstar/M2sec
fstar = 100
fstarM = fstar*M2sec
destar = 0.2
tminM = -10/M2sec
tmaxM = 0.0/M2sec
tmin, tmax = tminM*M2sec, tmaxM*M2sec


In [17]:
#Establish burst class
eb = EccBurstNew(q)
prior = NewPrior(tmin, tmax)

In [18]:
bursts = eb.get_all_bursts(tstarM, fstarM, destar, tminM, tmaxM)
tf_bursts_SI = np.array([[t*M2sec, f/M2sec, de] for t,f, de in bursts])

In [19]:
tf_bursts_SI

array([[-7.64384885e+00,  9.34212566e+01,  1.06100805e-02],
       [-6.25593939e+00,  9.45012354e+01,  4.84094874e-02],
       [-5.68467093e+00,  9.56884528e+01,  8.61983835e-02],
       [-5.36136762e+00,  9.69926618e+01,  1.24025119e-01],
       [-5.15000000e+00,  9.84253305e+01,  1.61940796e-01],
       [-5.00000000e+00,  1.00000000e+02,  2.00000000e-01],
       [-4.86292551e+00,  1.01574669e+02,  2.47232837e-01],
       [-4.76627567e+00,  1.03319918e+02,  2.96823590e-01],
       [-4.69527433e+00,  1.05260091e+02,  3.49043512e-01],
       [-4.64163519e+00,  1.07424888e+02,  4.04212418e-01],
       [-4.60031996e+00,  1.09850928e+02,  4.62710944e-01],
       [-4.56807390e+00,  1.12583930e+02,  5.24996884e-01],
       [-4.54269268e+00,  1.15681762e+02,  5.91627355e-01],
       [-4.52262556e+00,  1.19218843e+02,  6.63289444e-01],
       [-4.50674686e+00,  1.23292620e+02,  7.40843511e-01],
       [-4.49421747e+00,  1.28033402e+02,  8.25385913e-01],
       [-4.48439738e+00,  1.33619740e+02

In [20]:
#changed anchor burst to a different burst that is forward in time
tstar1 = -4.49421747
tstarM1 = tstar/M2sec
fstar1 = 128.033402
fstarM1 = fstar*M2sec
destar1 = 0.825
tminM1 = -10/M2sec
tmaxM1 = 0.0/M2sec
tmin1, tmax1 = tminM1*M2sec, tmaxM1*M2sec


In [21]:
bursts1 = eb.get_all_bursts(tstarM1, fstarM1, destar1, tminM1, tmaxM1)
tf_bursts_SI1 = np.array([[t*M2sec, f/M2sec, de] for t,f, de in bursts1])

In [22]:
tf_bursts_SI1

array([[-9.67913678e+00,  5.92689877e+01,  9.39888906e-02],
       [-9.05510824e+00,  5.96182721e+01,  1.10924433e-01],
       [-8.55621559e+00,  5.99823944e+01,  1.27866950e-01],
       [-8.14678282e+00,  6.03619749e+01,  1.44820903e-01],
       [-7.80388458e+00,  6.07576806e+01,  1.61790871e-01],
       [-7.51203650e+00,  6.11702290e+01,  1.78781557e-01],
       [-7.26035727e+00,  6.16003927e+01,  1.95797806e-01],
       [-7.04094933e+00,  6.20490050e+01,  2.12844619e-01],
       [-6.84792492e+00,  6.25169648e+01,  2.29927170e-01],
       [-6.67679399e+00,  6.30052436e+01,  2.47050819e-01],
       [-6.52406542e+00,  6.35148926e+01,  2.64221139e-01],
       [-6.38697885e+00,  6.40470505e+01,  2.81443928e-01],
       [-6.26331949e+00,  6.46029529e+01,  2.98725240e-01],
       [-6.15128716e+00,  6.51839429e+01,  3.16071404e-01],
       [-6.04940174e+00,  6.57914823e+01,  3.33489057e-01],
       [-5.95643376e+00,  6.64271656e+01,  3.50985174e-01],
       [-5.87135243e+00,  6.70927350e+01

In [23]:
#changed anchor burst to a burst that is backward in time
tstar2 = -5.68467093
tstarM2 = tstar/M2sec
fstar2 = 9.56884528e+01
fstarM2 = fstar*M2sec
destar2 = 0.825
tminM2 = -10/M2sec
tmaxM2 = 0.0/M2sec
tmin2, tmax2 = tminM2*M2sec, tmaxM2*M2sec

In [24]:
bursts2 = eb.get_all_bursts(tstarM2, fstarM2, destar2, tminM2, tmaxM2)
tf_bursts_SI2 = np.array([[t*M2sec, f/M2sec, de] for t,f, de in bursts2])

In [25]:
tf_bursts_SI2

array([[-9.67913678e+00,  5.92689877e+01,  9.39888906e-02],
       [-9.05510824e+00,  5.96182721e+01,  1.10924433e-01],
       [-8.55621559e+00,  5.99823944e+01,  1.27866950e-01],
       [-8.14678282e+00,  6.03619749e+01,  1.44820903e-01],
       [-7.80388458e+00,  6.07576806e+01,  1.61790871e-01],
       [-7.51203650e+00,  6.11702290e+01,  1.78781557e-01],
       [-7.26035727e+00,  6.16003927e+01,  1.95797806e-01],
       [-7.04094933e+00,  6.20490050e+01,  2.12844619e-01],
       [-6.84792492e+00,  6.25169648e+01,  2.29927170e-01],
       [-6.67679399e+00,  6.30052436e+01,  2.47050819e-01],
       [-6.52406542e+00,  6.35148926e+01,  2.64221139e-01],
       [-6.38697885e+00,  6.40470505e+01,  2.81443928e-01],
       [-6.26331949e+00,  6.46029529e+01,  2.98725240e-01],
       [-6.15128716e+00,  6.51839429e+01,  3.16071404e-01],
       [-6.04940174e+00,  6.57914823e+01,  3.33489057e-01],
       [-5.95643376e+00,  6.64271656e+01,  3.50985174e-01],
       [-5.87135243e+00,  6.70927350e+01